### ISSUE TITLE
Cuando subes un fest el logo de carga que indica que se está subiendo con depende que fondo no se ve NADA.

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#10]
### Comportamiento Actual

Cuando subes un fest el logo de carga que indica que se está subiendo con depende que fondo no se ve NADA.

### Comportamiento Esperado

Que se vea que carga algo

### Documentación Visual

No hay

**Comment by Albertomz99** [comment]
En FF se queda pillado y no se ve, pero debería estar ya solucionado.

**Comment by Albertomz99** [comment]
No funcionaba en build. He vuelto a editarlo.

**Comment by ASNUFATI** [comment]
Sale un cuadrado negro el bug se ha arreglado aunque entiendo que no va a ser definitivo por lo feo que queda
