### ISSUE TITLE
(SOLO EN ANDROID) GESTOS Y NAVEGACIÓN HACIA ATRAS 

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#102]
### Comportamiento Actual

Cuando en la pantalla del feed y de la lupa le das en el nav bar nativo de andorid hacia atras o con los gestos te sale de la aplicación 

### Comportamiento Esperado

Que te devuelva al android 

### Documentación Visual

No hay

**Comment by Growless** [comment]
Deberia estar solucionado en proxima build.

**Comment by ASNUFATI** [comment]
Como es en andorid y solo lo tiene dani, lo cierro aun asi estaremos pendientes con iñigo y gonzalo
