### ISSUE TITLE
Bloqueos 

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#105]
### Comportamiento Actual

Cuando sigues a un usuario y lo bloqueas y luego lo desbloqueas te aparece que le sigues siguiendo. 

### Comportamiento Esperado

Debería de dejarle de seguir automaticamente.

### Documentación Visual

No hay

**Comment by Growless** [comment]
Arreglado, marco para QA.

**Comment by ASNUFATI** [comment]
Hecho y testeado
