### ISSUE TITLE
CUENTA PROFESIONAL NO CAMBIA EL NAVBAR

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#107]
### Comportamiento Actual

A pesar de ser promotor con la cuenta de denibluu no me aparece en el NAVBAR el icono para entrar a la parte de empresa

### Comportamiento Esperado

Debería de aparecer 

### Documentación Visual

No hay.

**Comment by Growless** [comment]
Prueba de nuevo, seguramente fuese tema de la query de @Thesergiolg99

**Comment by ASNUFATI** [comment]
Correcto
