### ISSUE TITLE
Pantalla de privacidad de la cuenta. No funciona bien el privado/publico

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#11]
### Comportamiento Actual

Pantalla de privacidad de la cuenta. No funciona bien el privado/publico

### Comportamiento Esperado

Poder cambiarlo con tranquilidad

### Documentación Visual

no hay

**Comment by Thesergiolg99** [comment]
Ya está solucionado, lo escalo a diseño para que tito se pongo con ello

**Comment by ASNUFATI** [comment]
Tras el testeo funciona bien solo queda cambiar los colores

**Comment by Albertomz99** [comment]
Colores cambiados.
