### ISSUE TITLE
Las notificaciones no cambian de estado si no recargas la pagina

### ISSUE THREAD

**Issue by Growless** [Thesergiolg99/festify-issues#12]
### Comportamiento Actual

En la pagina de notificaciones, estas no cambian de estado al interactuar con los botones. Tienes que salir y volver a entrar a la página para ver cambios.

### Comportamiento Esperado

Las notificaciones deberían cambiar de estado sin salir de la página

### Pasos para Reproducir

1. Recibir nueva noti con botones que la hagan cambiar de estado 2. Inreactuar con los botones

### Documentación Visual

No nigga

**Comment by Thesergiolg99** [comment]
Debería estar listo en la próxima build (se esta subiendo)

**Comment by ASNUFATI** [comment]
funciona tras el testeo
