### ISSUE TITLE
NOTIFICACIONES Y TEXTO

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#13]
### Comportamiento Actual

No se ve el texto de "alejandro a aceptado tu solicitud" o "Alejandro ha comenzado a seguirte"

### Comportamiento Esperado

Que aparezca ese texto

### Documentación Visual

No hay, pero según lo cometado posiblemente sea por copiar y pegar

**Comment by Thesergiolg99** [comment]
Primer intento de resolución, estará en próxima build.

**Comment by Thesergiolg99** [comment]
Solved.
