### ISSUE TITLE
NO CARGA LOS FESTS DESTACADOS DE NINGUNA CUENTA

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#14]
### Comportamiento Actual

Se queda cargando en vez de mostrarlos 

### Comportamiento Esperado

que los muestre

### Documentación Visual

NO hay

**Comment by Thesergiolg99** [comment]
Alberto se fuma componentes sin avisar, arreglado y en proxima build disponible.
