### ISSUE TITLE
FUNCIONAMIENTO DEL MAPA

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#15]
### Comportamiento Actual

En ocasiones el mapa no abre y se queda cargando 

### Comportamiento Esperado

Que funcione

### Documentación Visual

No hay

**Comment by Growless** [comment]
Buena suerte

**Comment by Growless** [comment]
Debería esta solucionado.

**Comment by ASNUFATI** [comment]
Hecho y testeado
