### ISSUE TITLE
BOTO DE ACEPTAR SOLICITUDES A UNIONES A LOCALES DESDE EL PERFIL DE LOCAL

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#17]
### Comportamiento Actual

No hace nada aparentemente la otificación de aceptar solicitid de union al local, cuando recargas la pagina si 

### Comportamiento Esperado

Que funcione

### Documentación Visual

No hay

**Comment by Thesergiolg99** [comment]
Listo y en la build está ya metido.

**Comment by Growless** [comment]
Confirmo que funciona y cierro issue
