### ISSUE TITLE
En el perfil de empresa visto desde la vista de usuario normal los iconos que muestran info están muy oscuros

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#2]
### Comportamiento Actual

Un color mas claro

### Comportamiento Esperado

Que sea visible 

### Documentación Visual

No tengo imagen

**Comment by Albertomz99** [comment]
Falta mapear las condiciones a los iconos y sus colores.

**Comment by Thesergiolg99** [comment]
Ya debería esta todo mapeado, de colores no entiendo, pasa a visual de nuevo

**Comment by ASNUFATI** [comment]
Siguen oscuros
