### ISSUE TITLE
Falta el nombre del local en "EventosProfileRRPP" y "event"

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#22]
### Comportamiento Actual

.

### Comportamiento Esperado

.

### Documentación Visual

.

**Comment by Albertomz99** [comment]
Ya he añadido los parametros, solo falta mapearlos.

**Comment by Thesergiolg99** [comment]
Ya debería estar, al menos en en 80% de las llamadas a event, depende de donde se le llama el param cambia. Pongo QA review

**Comment by Growless** [comment]
Revierto la etiqueta QA Review, no está terminado

**Comment by Growless** [comment]
Arreglado y probado, marco para mas testing
