### ISSUE TITLE
En seeFestMentions, puedo verme a mí mismo mencionado.

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#23]
### Comportamiento Actual

Si estoy mencionado en un fest, seeFestMentions me muestra mi usuario, con su botón de Follow y redirigiéndome a mi perfil como userProfileOther.

### Comportamiento Esperado

- El botón de Follow no debería de verse (añadir ConditionalView)
- Si pulso en mi usuario/username/etc, debería llevarme a userProfile (en vez de UserProfileOther)

### Documentación Visual

.

**Comment by Growless** [comment]
Arreglado y testeado, marco como pendiente de revisión por el resto

**Comment by ASNUFATI** [comment]
Testeado ya no sales
