### ISSUE TITLE
En FollowersFollowingOther, puedo verme a mí mismo.

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#26]
### Comportamiento Actual

Si soy seguidor/seguido de otra cuenta, FollowersFollowingOther me muestra mi usuario, con su botón de Follow y redirigiéndome a mi perfil como userProfileOther.

### Comportamiento Esperado

- El botón de Follow no debería de verse (añadir ConditionalView)
- Si pulso en mi usuario/username/etc, debería llevarme a userProfile (en vez de UserProfileOther)

### Documentación Visual

.

**Comment by Growless** [comment]
El primer punto de la lista está solucionado. El segundo yo no haría de momento, ya que si haces un navigate a tu perfil de esa forma no aparecería el navbar y sería raro. ¿Qué hacemos?

**Comment by Albertomz99** [comment]
@Growless lo acabo de hablar con Sergio. No sé por qué me creía que teníamos ya hecho en algún lado el poder abrir el UserProfile mostrando el navbar.

Vamos a hacer que no puedas acceder a tu perfil desde vista ajena. Así que simplemente elimina toda las acciones que tengan la foto de perfil y username.

Tenemos que aplicarlo también en los otros lados donde se pueda ver tu propio username.
