### ISSUE TITLE
Se puede ver como mencionado en un fest a una cuenta que te tiene bloqueado.

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#28]
### Comportamiento Actual

- UserA tiene bloqueado a UserB.
- UserC sube un fest mencionando a UserA. 
- UserB ve el fest de UserC, y ve la mención de UserA, aunque este tiene bloqueado a UserB.

### Comportamiento Esperado

Si solo una persona es mencionada:
- No mostrar la row de mencionados.

Si hay más de una persona mencionada:
- Mostrar "<index - 1> personas" en el container de mencionados. Eliminar a la persona que te ha bloqueado de la lista.
- El componente de seeFestMentions se podrá abrir, pero no mostrará a a la persona que te ha bloqueado. Sí mostrará al resto de personas mencionadas.

### Documentación Visual

.

**Comment by Growless** [comment]
Arreglado y probado, marco como pendiente de testing.

**Comment by Albertomz99** [comment]
Reabro el ticket. Falta el siguiente comportamiento:

Si solo una persona es mencionada:

- No mostrar la row de mencionados.

Si hay más de una persona mencionada:

- Mostrar "<index - 1> personas" en el container de mencionados. Eliminar a la persona que te ha bloqueado de la lista.

**Comment by Growless** [comment]
Arreglado y probado, lo marco como pendiente de más testing.

**Comment by ASNUFATI** [comment]
TESTEADO
