### ISSUE TITLE
En nuestro mapa las ubicaciones de los locales están okay pero si pinchas para que te lleve a con el google maps no aparece (entiendo que no está mapeado)

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#3]
### Comportamiento Actual

En nuestro mapa las ubicaciones de los locales están okay pero si pinchas para que te lleve a con el google maps no aparece (entiendo que no está mapeado)

### Comportamiento Esperado

Que desaparezcan 

### Documentación Visual

No hay

**Comment by Thesergiolg99** [comment]
Se ha cambiado el código en Flutter y ya debería llevarte en los perfiles de empresa a la localización del establecimiento con el icono del mapa.

**Comment by ASNUFATI** [comment]
Tras el testeo todo okay
