### ISSUE TITLE
En createReaction, se puede spamear el botón de Send, dejando enviar la misma foto como diferentes reacciones.

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#30]
### Comportamiento Actual

.

### Comportamiento Esperado

Hacer como en UploadFest, que una vez se ha pulsado el botón no se puede ejecutar de nuevo.

Mirar ActionsFlow de UploadFest.

### Documentación Visual

.

**Comment by Growless** [comment]
Arreglado y probado, marco como pendiente de  más testing.
