### ISSUE TITLE
No se añade a usuarios como espectadores de un fest.

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#31]
### Comportamiento Actual

Solo se añaden a los usuarios como espectadores de un fest si le dan like al fest.

### Comportamiento Esperado

- Si ve el fest (no hace falta deslizar) se añade al usuario como espectador.

Preguntar a Alberto si hay dudas. Espectador vs Marcar fest como visto.

### Documentación Visual

.

**Comment by Thesergiolg99** [comment]
Ya lo hemos arreglado, en QA REVIEW

**Comment by Albertomz99** [comment]
@Growless @Thesergiolg99 Reabro el ticket. El comportamiento funciona en Descubre y Siguiendo, pero hay que aplicarlo también si se ve un fest desde el perfil del usuario o desde FestLugar.

**Comment by Thesergiolg99** [comment]
Que raro, he cambiado una cosilla a ver si era eso.

**Comment by ASNUFATI** [comment]
TESTEADO
