### ISSUE TITLE
SCROLL CUANDO VAS A ELEGIR LOS LUARES PARA ETIQUETARLO

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#32]
### Comportamiento Actual

No scroll haia abajo solo puedes elegir entre los primeros 

### Comportamiento Esperado

Que haga ese scroll para poder elegir el que se desee

### Documentación Visual

No

**Comment by Growless** [comment]
Esto es un problema de seleccionar el scroll en "lugaresCerca" (widget). Lo cambio a diseño.

**Comment by Albertomz99** [comment]
No puedo revisarlo en el pc por el tema de la localización.
