### ISSUE TITLE
CUANDO RECARGAS LA PAGINA DE TU PERFIL NO TE CUENTA TUS FESTS

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#34]
### Comportamiento Actual

Cuando recargas la pagina de tu perfil el contador cambia a 0 a pesar de tener 35 fests

### Comportamiento Esperado

Que no cambie ese contador

### Documentación Visual

No

**Comment by Thesergiolg99** [comment]
solucionado, QA Review

**Comment by ASNUFATI** [comment]
Testeado y arreglado
