### ISSUE TITLE
FOTOS DE PERFIL CUADRADAS EMPRESA

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#35]
### Comportamiento Actual

Dejamos las fotos de perfil de empresa cuadradas para diferenciar, pero luego si se ponen un png circular se ve circular no tiene mucho sentido o limitamos que no suban pngs o las dejamos circulares como las de los perfiles y que se diferencien con el tic narnaja 

### Comportamiento Esperado

A valorar

### Documentación Visual

No

**Comment by Albertomz99** [comment]
Es cosa de la imagen que seleccionó Sergio. No hay problema con ello.
