### ISSUE TITLE
COLORES DEL CALENDARIO PARA ASIGNAR EN LOS EVENTOS SE VEN NEGROS

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#38]
### Comportamiento Actual

No se diferencia bien para coger el dia y demas cuando vas a cambiar la hora a la que empieza un evento 

### Comportamiento Esperado

QUe se vea 

### Documentación Visual

NO

**Comment by Thesergiolg99** [comment]
Solucionado y en QA, hay que intentar ser más precisos en las issues y a ser posible foto del problema, nos ahorra tiempo.

**Comment by ASNUFATI** [comment]
Testeado y arreglado.
