### ISSUE TITLE
CUANDO EDITAS UN EVENTO NO ESTA MAPEADO EL LISTO

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#39]
### Comportamiento Actual

NO PUEDES GUARDAR LOS CAMBIOS CUANDO EDITAS EVENTO

### Comportamiento Esperado

Que vaya

### Documentación Visual

no

**Comment by Thesergiolg99** [comment]
Es problema de programación, ya está arreglado pero no refleja cambios, no lo cierro porque RRPPpage definitivamente necesita rework.

**Comment by Growless** [comment]
Está funcionando, marco para testing

**Comment by ASNUFATI** [comment]
Testeado y funciona
