### ISSUE TITLE
PARA EDITAR UN EVENTO NO HAY QUE DARle AL LAPIZ EN CUALQUIER PARTE DEL PANEL ES VALIDO

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#40]
### Comportamiento Actual

O quitamos el lapiz o ponemos que solo entre a edtiar el evento cuando des al lapiz 

### Comportamiento Esperado

decidirse

### Documentación Visual

no

**Comment by Albertomz99** [comment]
El lápiz indica que el container es tapeable y que permite editar el evento.
