### ISSUE TITLE
LIMITAR EVENTOS Y PROMOCIONES DEL SEARCH 

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#41]
### Comportamiento Actual

Quitar las que se pasen de fecha que te salgan solo de la fecha actual en adelante 

### Comportamiento Esperado

Que no aoarezcan eventos de enero

### Documentación Visual

no

**Comment by Growless** [comment]
Arreglado y probado, marco como pendiente de revisión

**Comment by Albertomz99** [comment]
Reabro el ticket. Siguen saliendo eventos expirados (e.g evento PATATON TRAVIESON, pene, ayayay. No puedo especificar el local porque no está mapeado).

Parece que el problema solo persiste con los eventos, las promociones parecen estar bien.

**Comment by Growless** [comment]
NO aparecen eventos expirados, la fecha que aparece es una diferente a la expiración (por modificar cosas directamente en bbdd), aconsejo que  crees nuevos eventos para probarlo

**Comment by ASNUFATI** [comment]
Podemos limpiar la BBDD de esa parte para probarlo bien no se sabe cuales están modificados y cuales no por lo que no se puede probar bien.

**Comment by ASNUFATI** [comment]
Lo cerre sin querer....

**Comment by Albertomz99** [comment]
@Growless @Thesergiolg99 podéis limpiar la BBDD? En lo que respecta a eventos y promos.

**Comment by Growless** [comment]
Issue antigua, en teoría funciona bien. Marco para testing
