### ISSUE TITLE
CUANDO EGENRAS UNA LISTA PANTALLAZO GRIS

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#42]
### Comportamiento Actual

Cuando vas a vincular un usuario a una lista un invitado pantallazo gris 

### Comportamiento Esperado

que funcione

### Documentación Visual

no

**Comment by Growless** [comment]
Arreglado y probado. Marco para testing por el resto del equipo

**Comment by Thesergiolg99** [comment]
Alguien modificó un textfield mal, cuidado con eso que supone romper cosas. Arreglado y entra en proxima build.

**Comment by ASNUFATI** [comment]
Arreglado y testeado
