### ISSUE TITLE
El container de mencionado de un fest (en Discover) no muestra el username del mencionado.

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#45]
### Comportamiento Actual

El container donde se muestran a las personas mencionadas en un fest, únicamente en Discover, no muestra el username de la persona mencionada, en caso de que solo se haya mencionado a 1 persona.

Se muestra el container vacío y el icono de persona mencionada, pero no el text del username.

### Comportamiento Esperado

Que el username sea visible.

### Documentación Visual

.

**Comment by Thesergiolg99** [comment]
He hecho movida en la bbdd y puede que me haya cargado algo, pero ya debería ir bien. QA REVIEW.
