### ISSUE TITLE
Cuenta profesional privada

### ISSUE THREAD

**Issue by Growless** [Thesergiolg99/festify-issues#47]
### Comportamiento Actual

Cuando tienes una cuenta privada y cambias a cuenta profesional se queda como cuenta privada

### Comportamiento Esperado

Debería cambiarse automáticamente a cuenta pública al cambiar a una cuenta profesional

### Documentación Visual

-

**Comment by Thesergiolg99** [comment]
Arreglado, estará en próxima build (no la de hoy)
