### ISSUE TITLE
Me salen mis propios fests en Descubre.

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#49]
### Comportamiento Actual

Podéis verlo en la cuenta de algunuser.

### Comportamiento Esperado

.

### Documentación Visual

.

**Comment by Growless** [comment]
@Thesergiolg99 ya sabemos que se jodió al cambiar la query

**Comment by Thesergiolg99** [comment]
gg xd, arreglado y en próxima build

**Comment by ASNUFATI** [comment]
TESTEADO
