### ISSUE TITLE
Tocar el username/profile pic de un usuario en una Notificación (newFollowerNotification y reactionNotification como mínimo) no lleva al perfil del usuario. Peta la pantalla (se queda en gris).

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#5]
### Comportamiento Actual

Tocar el username/profile pic de un usuario en una Notificación (newFollowerNotification y reactionNotification como mínimo) no lleva al perfil del usuario. Peta la pantalla (se queda en gris).

### Comportamiento Esperado

Preguntar a tito

### Documentación Visual

no hay

**Comment by Growless** [comment]
No he podido reproducirlo, necesita más testing por parte del resto

**Comment by Growless** [comment]
Se estuvo probando ayer y funcionaba bien, cierro el bug
