### ISSUE TITLE
Ocultar el apartado de privacidad de la cuenta de las cuentas profesionales

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#50]
### Comportamiento Actual

Ahora mismo aunque la cuenta pasa a ser pública cuando conviertes la cuenta a profesional, se puede volver a poner en privado desde los ajustes.

### Comportamiento Esperado

Añadir ConditionalView al apartado de Privacidad de la cuenta para que las cuentas profesionales no puedan acceder a esa pantalla.

### Documentación Visual

.

**Comment by Thesergiolg99** [comment]
Solucionado.

**Comment by ASNUFATI** [comment]
SIgue viendose le quito la etiqueta de QA @Thesergiolg99 @Growless
