### ISSUE TITLE
Bloquear a alguien debe eliminarle de tus Seguidores y tus Seguidos.

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#51]
### Comportamiento Actual

.

### Comportamiento Esperado

Cuando se bloquea a alguien, se debe:

- Eliminar a dicha cuenta de tus seguidores.
- Eliminarte de tus seguidos.

En caso de seguirle/que te siga.

### Documentación Visual

.

**Comment by Growless** [comment]
Fixed and tested.
