### ISSUE TITLE
No se eliminan las notificaciones de una cuenta que te ha bloqueado.

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#52]
### Comportamiento Actual

.

### Comportamiento Esperado

Cuando bloqueas una cuenta, se debe:

- Eliminar todas las notificaciones que esa cuenta tiene en las que estás referenciado.

### Documentación Visual

.

**Comment by Thesergiolg99** [comment]
repetida esta issue, tened cuidado. Solucionado.

**Comment by ASNUFATI** [comment]
TESTEADO
