### ISSUE TITLE
Si bloqueas a una cuenta que te sigue, se debe eliminar la notificación de seguimiento que tienes de esa cuenta.

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#53]
### Comportamiento Actual

.

### Comportamiento Esperado

Si bloqueas a una cuenta que te sigue, se debe eliminar la notificación de seguimiento que tienes de esa cuenta.

**Eliminar también la solicitud de seguimiento que se tenga de dicha cuenta. @Growless @Thesergiolg99** 

### Documentación Visual

.

**Comment by Thesergiolg99** [comment]
Debería estar ready en la proxima build
