### ISSUE TITLE
En FollowersFollowingOther, en la tab Seguidores, no muestra a usuarios que tengo bloqueado.

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#55]
### Comportamiento Actual

.

### Comportamiento Esperado

Debería poder ver a usuarios que YO he bloqueado (como en la tab Siguiendo).

### Documentación Visual

.

**Comment by Growless** [comment]
Yo voto por ocultar todas la apariciones de un usuario que has bloqueado. Pienso que la unica forma de verlo debería ser yendo especificamente a ver tus usuarios bloqueados.

**Comment by Growless** [comment]
@Albertomz99

**Comment by Albertomz99** [comment]
Ok. La única forma de ver un usuario que has bloqueado es desde el apartado de Cuentas bloqueadas de Settings.

**Comment by Growless** [comment]
Cierro issue pues
