### ISSUE TITLE
En Search, no se muestran las búsquedas recientes.

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#58]
### Comportamiento Actual

En Search, cuando se abre el teclado al tapear la search bar, no se abre/ve las búsquedas recientes.

### Comportamiento Esperado

Mostrar las búsquedas recientes.

Igual es un problema de la jerarquía con el componente de eventos y promos (cuanto más abajo está en la jerarquía un elemento, más prioridad tiene sobre el resto en caso de sobrelaparse).

### Documentación Visual

.

**Comment by Growless** [comment]
Arreglado (vista condicional de la lista de promos/events) y testeado.
