### ISSUE TITLE
Listas y su generación 

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#59]
### Comportamiento Actual

Actualmente cuando vas a crear una lista no deja rellenar el campo de la edad y el del DNI 

- El del DNI pinchas y como si no hiciera nada 
- El de la edad por el FORM se mueve el cero pero no me deja escribir 

### Comportamiento Esperado

Que funcione el rellenar la información 

### Documentación Visual

No es necesario

**Comment by Thesergiolg99** [comment]
Esto está hecho así aposta, que diga @Albertomz99 si se debe cambiar su forma de ser.
