### ISSUE TITLE
En FollowingFollowerOther, no puedo ver el Siguiendo de una cuenta a la que he bloqueado.

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#60]
### Comportamiento Actual

.

### Comportamiento Esperado

Mostrar los usuarios de Siguiendo (como sucede con los Seguidores).

### Documentación Visual

.

**Comment by Thesergiolg99** [comment]
No entiendo:

Te refieres a que no se debe ver ahí usuarios los cuales yo he bloqueado verdad?

**Comment by Thesergiolg99** [comment]
@Albertomz99 Vamos a leer el github, te puse un comment hace 3 dias
