### ISSUE TITLE
Proceso eliminar seguidor desde FollowingFollower

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#61]
### Comportamiento Actual

Ahora mismo, presionas en Eliminar/Remove y:

- Elimina al usuario de tus seguidores.
- Sigues viendo al usuario en el listado, ahora con el botón mostrando "Eliminado".

### Comportamiento Esperado

Al pulsar el botón Eliminar/Remove, se llama al bottomsheet removeFollowerConfirmation.

En el bottomsheet, debemos:

- Mapear la foto de perfil con el usuario en cuestión.
- Mapear el texto de username en el CombineText.
- Pulsar el botón de Eliminar cierra el pop up y elimina al usuario de tus seguidores. También hace que desaparezca automáticamente del listado visible.
- Pulsar el botón de Cancelar cierra el bottomsheet.

### Documentación Visual

.

**Comment by Albertomz99** [comment]
Overflow en el bottomsheet.

**Comment by Thesergiolg99** [comment]
A falta del fix de tito de diseño la funcionalidad está implementada.
