### ISSUE TITLE
En EventoCompra, ocultar el título de Reservas y el mapa si no hay ningún reservado disponible.

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#63]
### Comportamiento Actual

.

### Comportamiento Esperado

.

### Documentación Visual

.

**Comment by Thesergiolg99** [comment]
Debería estar listo. QA

**Comment by Albertomz99** [comment]
Se siguen viendo tanto el título de "Reservas" como el mapa.

**Comment by Growless** [comment]
La cierro ya que, tras el rework, veremos como queda este tema
