### ISSUE TITLE
El tipoLugar de una empresa en los perfiles no muestra correctamente el local

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#69]
### Comportamiento Actual

En ProfileEmpresa y ProfileEmpresaOther, el texto de tipoLugar que se muestra debajo del display name (al lado de los seguidores), no muestra correctamente si el establecimiento es un Local o una Discoteca. Aparece Establecimiento todo el rato.

### Comportamiento Esperado

.

### Documentación Visual

.

**Comment by Growless** [comment]
No se estaban creando correctamente los establecimientos con su tipo correspondiente, marco como pendiente de pruebas para proxima build.

**Comment by ASNUFATI** [comment]
A
