### ISSUE TITLE
En EventoCompra, la tag de etiqueta no está mapeada.

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#71]
### Comportamiento Actual

.

### Comportamiento Esperado

Mostrar el valor asignado a la etiqueta al crear el evento.

### Documentación Visual

.

**Comment by Albertomz99** [comment]
Aún lo tengo que probar en el editor.

**Comment by Albertomz99** [comment]
@Growless @Thesergiolg99 he quitado lo que he tocado porque no parece funcionar. Chequeadlo.

**Comment by Growless** [comment]
Done
