### ISSUE TITLE
Registro nuevo

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#73]
### Comportamiento Actual

Cuando estas en el proceso de inicio de sesión llegas al ultimo paso y le das para volver hacia detras te saca a una especia de feed como si tuvieras la cuenta creada, pero claro esta todo vacio por que no hay nada creado entonces si te mueves por el nav bar te salen pantallazos grises 

### Comportamiento Esperado

Que al volver hacia atras en la ultima pantalla (la primera si haces el flujo de inicio de sesión) no te deje volver hacia detras.

### Documentación Visual

![IMG_1169 2](https://github.com/Thesergiolg99/festify-issues/assets/169722904/89221724-82e7-47c0-93f7-3d9d61509597)

**Comment by Growless** [comment]
@ASNUFATI No he conseguido replicarlo, entiendo que te refieres al flujo de creación de un usuario, no a inicio de sesión.

**Comment by Thesergiolg99** [comment]
Tampoco he sido capaz :(

**Comment by ASNUFATI** [comment]
Hay que darle a la flechita de arriba a la derecha cuando estas en el flujo de registro y te lleva ahi el problema es que he puesto inicio y es en el flujo de registro le cambio el nombre

**Comment by Thesergiolg99** [comment]
Deberia estar ready en la proxima update

**Comment by ASNUFATI** [comment]
Revisado y hecho
