### ISSUE TITLE
Flujo de Inicio de sesión 

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#74]
### Comportamiento Actual

Cuando inicias sesión con google cuando metes tu cuenta de google el siguiente paso se solapa con el de creación de empresa 

### Comportamiento Esperado

que siga el flujo esperado

### Documentación Visual

![IMG_1165 2](https://github.com/Thesergiolg99/festify-issues/assets/169722904/30641cc6-1276-4196-8ba0-50f310fb5b09)
![IMG_1166 2](https://github.com/Thesergiolg99/festify-issues/assets/169722904/71e537e0-85ab-44f7-9f2a-e54a59c7aa43)
![IMG_1167 2](https://github.com/Thesergiolg99/festify-issues/assets/169722904/024e4a29-1f69-4c0f-85e8-cc28b7df04a0)
![IMG_1168 2](https://github.com/Thesergiolg99/festify-issues/assets/169722904/0898509a-8dd3-4180-b979-404a54dc449a)

**Comment by ASNUFATI** [comment]
También @Albertomz99 habría que colocar los forms? o es que como se solapa en el flujo este que sigue no estan pero como no es correcto nos da igual

**Comment by ASNUFATI** [comment]
Por otro lado, a este bug si cuando te sale este flujo reinicias la app te vuelve a meter en el flujo que es con la cuenta de google "metida" @Growless y @Thesergiolg99

**Comment by Albertomz99** [comment]
Eso es que no se setea bien la variable registerEsEmpresa

@Thesergiolg99 @Growless
