### ISSUE TITLE
Destacados gris

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#76]
### Comportamiento Actual

Cuando terminas de crearte la cuenta, y te vas a tu perfil deberia de estar vacio pero tienes como los tres primeros espacios de los fests rellenos de color gris 

### Comportamiento Esperado

Que saliera vacío

### Documentación Visual

![IMG_1170](https://github.com/Thesergiolg99/festify-issues/assets/169722904/fa45dd5e-e79d-47c9-bc31-6833ec9378e6)

**Comment by Thesergiolg99** [comment]
Solved, buen punto.
