### ISSUE TITLE
Añadir mapas en las reservas.

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#78]
### Comportamiento Actual

.

### Comportamiento Esperado

En Reservas:
- Al pulsar el container, debe abrir la opción de cámara/galería.
- Cuando se seleccione una imagen, se mostrará en el container.
- El comportamiento de añadir una imagen sigue aun cuando ya hay una imagen seleccionada.

En EventoCompra
- La imagen seleccionada aparecerá en el container de mapa (de la sección Reservados).
- Si se pulsa el container, se mostrará la imagen en grande (expandImage).

### Documentación Visual

.

**Comment by Growless** [comment]
Done, marco para más testing
