### ISSUE TITLE
Notificación like

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#79]
### Comportamiento Actual

.

### Comportamiento Esperado

Cuando userA da like al fest de userB, se creará una notificación para userB.

Notificación:
- Texto: "A <username> le ha gustado tu fest".
- Stack: Container con la imagen del fest + Container barrierColor + Texto ("Ver")

- Tapear en el username lleva al perfil de dicho usuario.
- Tapear en el resto de la row o en la imagen: 1. Redirige al fest 2. Abre el bottomsheet festReactions (en la tab Espectadores).

No mostrar la notificación si me doy like a un fest mío.

### Documentación Visual

.

**Comment by Thesergiolg99** [comment]
Listo.
