### ISSUE TITLE
Cuando vas a reservar un reservado el precio no entra dentro del cuadrado bug visual

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#8]
### Comportamiento Actual

Cuando vas a reservar un reservado el precio no entra dentro del cuadrado bug visual

### Comportamiento Esperado

No overflow

### Documentación Visual

No hay

**Comment by Albertomz99** [comment]
@ASNUFATI puedes pasar captura? Estoy mirando en la app y me sale bien.

**Comment by ASNUFATI** [comment]
![IMG_BE61286DF152-1](https://github.com/Thesergiolg99/festify-issues/assets/169722904/85d4f7ef-eb56-4b81-80d7-055b3dc3036c)
@Albertomz99
