### ISSUE TITLE
Redireccionar cuando se tapea un contenido en search.

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#80]
### Comportamiento Actual

.

### Comportamiento Esperado

Cuando tapeas un contenido en search:

- Si es una promoción, redirecciona al perfil de la empresa que ha subido la promo.
- Si es un flyer, redirecciona a eventoCompra (del evento en cuestión).

### Documentación Visual

.

**Comment by Growless** [comment]
Done, marco para mas testing.

**Comment by ASNUFATI** [comment]
Testeado. funcionando
