### ISSUE TITLE
Display Name

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#81]
### Comportamiento Actual

Cuando entras en el perfil de otro no aparece el display name en el perfil

### Comportamiento Esperado

Saber por lo menos como se llama

### Documentación Visual

![IMG_2DB3004B1733-1](https://github.com/Thesergiolg99/festify-issues/assets/169722904/a9a06138-86d2-4416-92e4-ddc5b6ac2729)

**Comment by Growless** [comment]
@Albertomz99, @Thesergiolg99  Ideas? Yo opino que con el nombre de usuario arriba es suficiente.

**Comment by Growless** [comment]
@Albertomz99 lo solucionó, era un bug. Cierro issue.
