### ISSUE TITLE
PERFIL PROPIO

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#82]
### Comportamiento Actual

Cuando le das al contador de los fests de tu perfil a pesar de tener (en el caso de la cuenta de alejandro 25) no te enseña nada mas que un "No items found"

### Comportamiento Esperado

Poder verlos de ahí? O que no te lleve a ningún lado

### Documentación Visual

![IMG_AAD9AB5BE56A-1](https://github.com/Thesergiolg99/festify-issues/assets/169722904/d9836640-1c5a-4a22-a917-6f790467a3ff)

**Comment by Growless** [comment]
No es un bug, es una prueba de @Albertomz99. Para evitar estos malentendidos lo mejor sería  hacer las pruebas cambiando momentáneamente la página donde queremos probar por una copia y luego dejarlo como estaba en cuanto se haya probado.
Cierro issue.
