### ISSUE TITLE
VISUALIZACIÓN DE FESTS

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#83]
### Comportamiento Actual

En todos los sitios que se pueden visualizar cadenas de fests aleatoriamente no se muestra uno y se queda en "negro"

### Comportamiento Esperado

Deberían mostrarse todos

### Documentación Visual

No hay

**Comment by Thesergiolg99** [comment]
Con la nueva build cambie muchas queries, please testead y a ver si no pasa, de momento ya no lo replico

**Comment by ASNUFATI** [comment]
Yo tampoco he conseguido replicarlo de nuevo por lo que lo doy por cerrado
