### ISSUE TITLE
No funciona EditFestsDestacados

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#85]
### Comportamiento Actual

.

### Comportamiento Esperado

.

### Documentación Visual

.

**Comment by Thesergiolg99** [comment]
Lo mismo que te he dicho por el grupo, tratad de evidenciar los issues y así nos ahorráis tiempo a @Growless y a mi en descrubrir el error.

(Ya esta fixed y en QA review para proxima build)
