### ISSUE TITLE
Notificaciones usuario 

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#86]
### Comportamiento Actual

en las notificaciones me salen 4 cuadrados sin texto entiendo que falta el texto para categorizar los tipo de notificaciones

### Comportamiento Esperado

Que esten indicados 

### Documentación Visual

![IMG_730B03C05B35-1](https://github.com/Thesergiolg99/festify-issues/assets/169722904/c93f6bf7-adb5-4868-bedd-f6755bacfa98)

**Comment by Albertomz99** [comment]
Es una prueba del sistema de filtrado de notificaciones.
