### ISSUE TITLE
Inicio de sesión 

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#87]
### Comportamiento Actual

Cuando inicas sesión y fallas en el username no sale ningun mensaje de error sin embargo cuando fallas la contraseña si 

### Comportamiento Esperado

Que salga mensaje de error

### Documentación Visual

no hay

**Comment by Thesergiolg99** [comment]
Eso ya dije en su día por qué y además es una tarea que teníais pendiente de hacer @ASNUFATI @Albertomz99, la traduccion que si te sale es la que os puse yo a modo de ejemplo.

<img width="1074" alt="image" src="https://github.com/Thesergiolg99/festify-issues/assets/72013520/0a96c8a8-5f2f-416d-b8c6-4b3601222e0d">

**Comment by ASNUFATI** [comment]
Okay en teoria ya estan tosdaas las traducciones esas metidas, para la siguiente build estará.
