### ISSUE TITLE
EditFestDestacados (tab Todos los fests) no permite quitar fests de destacados.

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#90]
### Comportamiento Actual

En la tab de todos los fests de EditFestDestacados, no se pueden quitar fests destacados, solo deja destacarlos.

### Comportamiento Esperado

En la tab de todos los fests de EditFestDestacados, cuando tocas un fest destacado, se eliminará de destacados.

### Documentación Visual

.

**Comment by Thesergiolg99** [comment]
Arreglado

**Comment by ASNUFATI** [comment]
Arreglado y testeado
