### ISSUE TITLE
Vista rápida de resultados y vista de todos los resultados se sobrelapan

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#91]
### Comportamiento Actual

Cuando vas a buscar un usuario por ejemplo (alejandrooo.sn) un en el buscador pones (al) y te busca 5 usuarios si le das a ver mas resultados se te duplican los usuarios que ya estaban mostrados por que no se ocultan.

### Comportamiento Esperado

Deberían de no salir duplicados 

### Documentación Visual

![IMG_F28A6BD34D22-1](https://github.com/user-attachments/assets/ac50ff71-9e97-4eb2-a16e-a5f78d70be37)

**Comment by Growless** [comment]
Solucionado. Marco como pendiente de testing

**Comment by ASNUFATI** [comment]
Hecho y testado
