### ISSUE TITLE
Editar foto en EditProfile debe permitir cambiar la foto.

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#92]
### Comportamiento Actual

No hace nada al tapear.

### Comportamiento Esperado

Pantalla EditProfile

Al tapear en el texto, se debería poder cambiar la foto de perfil. Mismo comportamiento que la imagen de foto de perfil.

### Documentación Visual

.

**Comment by Thesergiolg99** [comment]
Done

**Comment by ASNUFATI** [comment]
Testeado y funciona
