### ISSUE TITLE
Falta arrow navigate back en festview desde FestLugar

### ISSUE THREAD

**Issue by Albertomz99** [Thesergiolg99/festify-issues#93]
### Comportamiento Actual

Actualmente cuando vas a ver un fest de FestLugar, no se puede volver atrás.

### Comportamiento Esperado

- Añadir icono flecha hacia atrás.
- Mapear icono para que te mande a festLugar.
- El icono solo debe ser visible si se entra desde festLugar.

### Documentación Visual

.

**Comment by Thesergiolg99** [comment]
Done

**Comment by ASNUFATI** [comment]
Hecho y testeado
