### ISSUE TITLE
SUGERENCIAS

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#94]
### Comportamiento Actual

Cuando no hay fests subidos por tus seguidores te aparexe la pestaña de sugerencias, si le das a seguir no se guarda esa solicitud por lo que no sigues al usuario

### Comportamiento Esperado

Que le puedas seguir

### Documentación Visual

IMG_551D5F2ECFD8-1
![IMG_551D5F2ECFD8-1](https://github.com/user-attachments/assets/a4badd97-f36c-4b58-8631-215ccbae8bb3)

**Comment by Growless** [comment]
Solucionado, marco para QAReview.

**Comment by ASNUFATI** [comment]
Hecho y testeado
