### ISSUE TITLE
FESTS A DESTACAR

### ISSUE THREAD

**Issue by ASNUFATI** [Thesergiolg99/festify-issues#95]
### Comportamiento Actual

Cuando vas a seleccionar los fests que vas a destacar el APP BAR sale descolocada en dos lineas

### Comportamiento Esperado

En una linea el texto 

### Documentación Visual

no hay

**Comment by Albertomz99** [comment]
@ASNUFATI añade una captura, no consigo reproducirlo.

**Comment by ASNUFATI** [comment]
![IMG_D3AE18633AD9-1](https://github.com/user-attachments/assets/d8f7558d-c679-4058-aa1c-6bf5f94ac3d5)
Era aquí y ya sale colocado por lo que lo damos por cerrado, pero si te acuerdas este le vi contigo.
